### PR TITLE
Other layers implementation

### PR DESCRIPTION
**Pull request by cypo721**
Implementation of Rest, Facade and partial Service layer.

### CODE REVIEW

**Comment by ondrejvelisek** [comment]
Cau, Vypada to dobre, ale nejde to zkompilovat.

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/ondrejvelisek/projects/events-shop/events-shop-rest/src/main/java/cz/muni/fi/eventsshop/rest/ServiceRestImpl.java:[27,22] cannot find symbol
  symbol:   method getAllServices()
  location: variable facade of type cz.muni.fi.eventsshop.facade.ServiceFacade

Muzes do commitu pridat nejake protezy, at to slape?

**Comment by cypo721** [comment]
Sorry. Updatoval som commit, uz by to malo ist.

**Comment by ondrejvelisek** [comment]
Super. Uz to jde zkompilovat, ale porad to nejde spustit. :-D 

DeploymentException: WELD-001408: Unsatisfied dependencies for type ServiceService with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private cz.muni.fi.eventsshop.facade.ServiceFacadeImpl.service
  at cz.muni.fi.eventsshop.facade.ServiceFacadeImpl.service(ServiceFacadeImpl.java:0)

**Comment by cypo721** [comment]
Nad petovou persistance dokoncene ostatne vrstvy. 
Taktiez je tu implementovane volanie weather API.
Projekt mi siel pustit a nasadit cez IDEU na wildfly, ale mvn:wildfly run mi nefungoval.

**Pull request merged**
